"""oi

Revision ID: 067aa7faea60
Revises: 
Create Date: 2024-08-30 08:23:57.970075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067aa7faea60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carros',
    sa.Column('id_carros', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('ano', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id_carros')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Carros')
    # ### end Alembic commands ###
