"""Create table Carros

Revision ID: 426dd72db60d
Revises: 
Create Date: 2024-08-23 08:17:49.343822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426dd72db60d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carros',
    sa.Column('id_carros', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_carros')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Carros')
    # ### end Alembic commands ###
